package app.voyager;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.jdbc.core.JdbcTemplate;
import java.util.*;
import java.util.concurrent.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:collaboration;DB_CLOSE_DELAY=-1","voyager.dev-login=true"})
@AutoConfigureMockMvc
class CollaborationTest {
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate db;@Autowired TripService trips;@Autowired AuthService auth;
 String a,b,c;JsonNode payload;
 @BeforeEach void setup()throws Exception{for(String table:List.of("operations","invites","members","trips","sessions","app_users"))db.update("DELETE FROM "+table);a=login("student-a");b=login("student-b");c=login("student-c");payload=json.readTree("""
 {"trip":{"id":"local-t","destination":"杭州","startDate":"2026-10-09","endDate":"2026-10-09","totalBudget":600,"itinerary":[{"id":"day-1","date":"2026-10-09","activities":[{"id":"activity-1","name":"西湖湖滨","time":"09:00"}]}],"aaMembers":[{"id":"m1","name":"甲"},{"id":"m2","name":"乙"}],"aaSettlements":[]},"expenses":[{"id":"e1","tripId":"local-t","amount":10,"date":"2026-10-09","description":"午餐","category":"food","split":{"version":1,"payerId":"m1","shares":[{"memberId":"m1","cents":500},{"memberId":"m2","cents":500}]}}]}
 """);}
 String login(String account)throws Exception{return call("/api/auth/dev",Map.of("account",account),null,200).path("token").asText();}
 JsonNode call(String url,Object body,String token,int expected)throws Exception{var request=post(url).contentType("application/json").content(json.writeValueAsString(body));if(token!=null)request.header("Authorization","Bearer "+token);String raw=mvc.perform(request).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return raw.isBlank()?json.nullNode():json.readTree(raw);}
 JsonNode create()throws Exception{return call("/api/trips",Map.of("operationId","upload-123","payload",payload),a,200);}
 JsonNode invite(String id,String role)throws Exception{return call("/api/trips/"+id+"/invites",Map.of("role",role),a,200);}
 void update(String id,String token,long version,JsonNode p,int status)throws Exception{mvc.perform(put("/api/trips/"+id).header("Authorization","Bearer "+token).contentType("application/json").content(json.writeValueAsString(Map.of("version",version,"payload",p)))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().is(status));}
 @Test void authenticationAndLogout()throws Exception{mvc.perform(get("/api/health")).andExpect(status().isOk()).andExpect(jsonPath("$.devLogin").value(true));mvc.perform(get("/api/trips")).andExpect(status().isUnauthorized());call("/api/auth/logout",Map.of(),a,200);mvc.perform(get("/api/trips").header("Authorization","Bearer "+a)).andExpect(status().isUnauthorized());call("/api/auth/wechat",Map.of("code","dummy"),null,503);}
 @Test void sharedReadEditorAndOutsider()throws Exception{String id=create().path("id").asText();var invitation=invite(id,"editor");call("/api/invites/join",Map.of("token",invitation.path("token").asText()),b,200);mvc.perform(get("/api/trips/"+id).header("Authorization","Bearer "+c)).andExpect(status().isNotFound());var changed=payload.deepCopy();((ObjectNode)changed.path("trip")).put("destination","北京");update(id,b,1,changed,200);var after=trips.get(id,auth.user("Bearer "+a));assertEquals("北京",((JsonNode)after.get("payload")).path("trip").path("destination").asText());assertEquals(2L,after.get("version"));}
 @Test void viewerCannotWriteOrInviteAndOwnerCannotBeDowngraded()throws Exception{String id=create().path("id").asText();String token=invite(id,"viewer").path("token").asText();call("/api/invites/join",Map.of("token",token),b,200);update(id,b,1,payload,403);call("/api/trips/"+id+"/invites",Map.of("role","editor"),b,403);var owner=call("/api/invites/join",Map.of("token",token),a,200);assertEquals("owner",owner.path("role").asText());}
 @Test void expiredRevokedAndRepeatedInvite()throws Exception{String id=create().path("id").asText();String token=invite(id,"editor").path("token").asText();call("/api/invites/join",Map.of("token",token),b,200);call("/api/invites/join",Map.of("token",token),b,200);assertEquals(2,db.queryForObject("SELECT COUNT(*) FROM members WHERE trip_id=?",Integer.class,id));call("/api/trips/"+id+"/invites/revoke",Map.of("token",token),a,200);call("/api/invites/join",Map.of("token",token),c,410);String expired=invite(id,"viewer").path("token").asText();db.update("UPDATE invites SET expires_at=0 WHERE token_hash=?",AuthService.hash(expired));call("/api/invites/join",Map.of("token",expired),c,410);}
 @Test void idempotentCreateAndConflict()throws Exception{String id=create().path("id").asText();assertEquals(id,create().path("id").asText());var changed=payload.deepCopy();((ObjectNode)changed.path("trip")).put("destination","成都");call("/api/trips",Map.of("operationId","upload-123","payload",changed),a,409);assertEquals(1,db.queryForObject("SELECT COUNT(*) FROM trips",Integer.class));update(id,a,1,payload,200);update(id,a,1,payload,409);}
 @Test void concurrentVersionsOnlyOneSucceeds()throws Exception{String id=create().path("id").asText(),user=auth.user("Bearer "+a);try(var pool=Executors.newFixedThreadPool(2)){var ready=new CountDownLatch(2);var go=new CountDownLatch(1);Callable<Integer> job=()->{ready.countDown();go.await();try{trips.update(id,user,1,payload);return 200;}catch(ApiError e){return e.status;}};var first=pool.submit(job);var second=pool.submit(job);ready.await();go.countDown();assertEquals(Set.of(200,409),Set.of(first.get(),second.get()));}}
 @Test void validationPreventsBrokenAAAndBadDate()throws Exception{var bad=payload.deepCopy();((ObjectNode)bad.path("expenses").get(0).path("split").path("shares").get(0)).put("cents",501);call("/api/trips",Map.of("operationId","upload-123","payload",bad),a,400);((ObjectNode)bad.path("trip")).put("startDate","2026-02-30");call("/api/trips",Map.of("operationId","upload-456","payload",bad),a,400);assertEquals(0,db.queryForObject("SELECT COUNT(*) FROM trips",Integer.class));}
 @Test void devLoginIsLoopbackOnlyAndSessionsAreHashed()throws Exception{mvc.perform(post("/api/auth/dev").with(r->{r.setRemoteAddr("192.168.1.12");return r;}).contentType("application/json").content("{\"account\":\"student-a\"}")).andExpect(status().isForbidden());assertEquals(0,db.queryForObject("SELECT COUNT(*) FROM sessions WHERE token_hash=?",Integer.class,a));}

 @Autowired MutationService mutations;
 JsonNode action(String id,String token,long version,String operation,String action,Map<String,Object> data,int status)throws Exception{return call("/api/trips/"+id+"/actions",Map.of("version",version,"operationId",operation,"action",action,"data",data),token,status);}
 Map<String,Object> expenseData(double amount,boolean shared){var data=new HashMap<String,Object>();data.put("amount",amount);data.put("shared",shared);data.put("description","午餐");data.put("date","2026-10-09");data.put("category","food");if(shared){data.put("payerId","m1");data.put("participantIds",List.of("m2","m1"));}return data;}
 @Test void expenseAddEditDeleteAndExactLedger()throws Exception{String id=create().path("id").asText();var added=action(id,b,1,"expense-denied","addExpense",expenseData(2,false),404);added=action(id,a,1,"expense-add-1","addExpense",expenseData(2,false),200);assertEquals(1200,added.path("ledger").path("totalCents").asLong());String expenseId=added.path("payload").path("expenses").get(1).path("id").asText();var data=expenseData(3,false);data.put("id",expenseId);var edited=action(id,a,2,"expense-edit-1","updateExpense",data,200);assertEquals(1300,edited.path("ledger").path("totalCents").asLong());data.put("shared",true);action(id,a,3,"expense-convert","updateExpense",data,400);var deleted=action(id,a,3,"expense-delete","deleteExpense",Map.of("id",expenseId),200);assertEquals(1000,deleted.path("ledger").path("totalCents").asLong());}
 @Test void aaEditPreservesOfflineSettlementAndReplay()throws Exception{String id=create().path("id").asText();var settle=Map.<String,Object>of("fromId","m2","toId","m1","cents",500);var paid=action(id,a,1,"settlement-1","settle",settle,200);var repeated=action(id,a,1,"settlement-1","settle",settle,200);assertEquals(2,repeated.path("version").asLong());assertEquals(1,repeated.path("ledger").path("settlements").size());action(id,a,2,"settlement-2","settle",settle,400);var data=expenseData(20,true);data.put("id","e1");var edited=action(id,a,2,"expense-shared","updateExpense",data,200);assertEquals(500,edited.path("ledger").path("members").get(0).path("balanceCents").asLong());assertEquals(2000,edited.path("ledger").path("totalCents").asLong());var undone=action(id,a,3,"settlement-undo","undoSettlement",Map.of("id",paid.path("ledger").path("settlements").get(0).path("id").asText()),200);assertEquals(1000,undone.path("ledger").path("members").get(0).path("balanceCents").asLong());}
 @Test void memberRenameRemovalAndOneCent()throws Exception{String id=create().path("id").asText();var added=action(id,a,1,"member-add-1","addMember",Map.of("name","丙"),200);String member=added.path("payload").path("trip").path("aaMembers").get(2).path("id").asText();action(id,a,2,"member-rename","renameMember",Map.of("id","m1","name","小甲"),200);action(id,a,3,"member-remove-bad","removeMember",Map.of("id","m1"),400);var removed=action(id,a,3,"member-remove-good","removeMember",Map.of("id",member),200);assertEquals(2,removed.path("ledger").path("members").size());var cent=action(id,a,4,"one-cent-add","addExpense",expenseData(0.01,true),200);assertEquals(1001,cent.path("ledger").path("sharedCents").asLong());var shares=cent.path("payload").path("expenses").get(1).path("split").path("shares");assertEquals(1,shares.get(0).path("cents").asLong());assertEquals(0,shares.get(1).path("cents").asLong());}
 @Test void activitiesAddEditMoveDeletePreserveDay()throws Exception{String id=create().path("id").asText();var data=new HashMap<String,Object>(Map.of("dayId","day-1","name","断桥","time","11:00","notes","步行游览"));var added=action(id,a,1,"activity-add","addActivity",data,200);String activity=added.path("payload").path("trip").path("itinerary").get(0).path("activities").get(1).path("id").asText();data.put("id",activity);data.put("name","雷峰塔");action(id,a,2,"activity-edit","updateActivity",data,200);var moved=action(id,a,3,"activity-move","moveActivity",Map.of("dayId","day-1","id",activity,"targetIndex",0),200);assertEquals("雷峰塔",moved.path("payload").path("trip").path("itinerary").get(0).path("activities").get(0).path("name").asText());action(id,a,4,"activity-delete1","deleteActivity",Map.of("dayId","day-1","id",activity),200);var empty=action(id,a,5,"activity-delete2","deleteActivity",Map.of("dayId","day-1","id","activity-1"),200);assertEquals(1,empty.path("payload").path("trip").path("itinerary").size());assertEquals(0,empty.path("payload").path("trip").path("itinerary").get(0).path("activities").size());}
 @Test void viewerAndOutsiderCannotMutate()throws Exception{String id=create().path("id").asText();String token=invite(id,"viewer").path("token").asText();call("/api/invites/join",Map.of("token",token),b,200);for(String act:List.of("addExpense","deleteExpense","settle","undoSettlement","addMember","renameMember","removeMember","addActivity","moveActivity","deleteActivity")){action(id,b,1,"viewer-denied-"+act,act,Map.of(),403);action(id,c,1,"outsider-denied-"+act,act,Map.of(),404);}assertEquals(1L,trips.get(id,auth.user("Bearer "+a)).get("version"));}
 @Test void concurrentActionsOnlyOneCommits()throws Exception{String id=create().path("id").asText(),user=auth.user("Bearer "+a);try(var pool=Executors.newFixedThreadPool(2)){var ready=new CountDownLatch(2);var go=new CountDownLatch(1);Callable<Integer> job=()->{ready.countDown();go.await();try{mutations.apply(id,user,1,"parallel-"+UUID.randomUUID(),"addExpense",json.valueToTree(expenseData(2,false)));return 200;}catch(ApiError e){return e.status;}};var first=pool.submit(job);var second=pool.submit(job);ready.await();go.countDown();assertEquals(Set.of(200,409),Set.of(first.get(),second.get()));}assertEquals(2,((JsonNode)trips.get(id,auth.user("Bearer "+a)).get("payload")).path("expenses").size());}
 @Test void rawPutCannotBypassFinancialActions()throws Exception{String id=create().path("id").asText();var changed=payload.deepCopy();((ObjectNode)changed.path("expenses").get(0)).put("amount",20);((ObjectNode)changed.path("expenses").get(0).path("split").path("shares").get(0)).put("cents",1000);((ObjectNode)changed.path("expenses").get(0).path("split").path("shares").get(1)).put("cents",1000);update(id,a,1,changed,400);assertEquals(1L,trips.get(id,auth.user("Bearer "+a)).get("version"));}
 @Test void invalidCommandRollsBackAndCannotReuseOperationForOtherData()throws Exception{String id=create().path("id").asText();var data=expenseData(2,true);data.put("participantIds",List.of("m1","m1"));action(id,a,1,"invalid-expense","addExpense",data,400);action(id,a,1,"invalid-time","addActivity",Map.of("dayId","day-1","name","西湖","time","99:99"),400);assertEquals(0,db.queryForObject("SELECT COUNT(*) FROM operations",Integer.class));action(id,a,1,"valid-expense","addExpense",expenseData(2,false),200);action(id,a,1,"valid-expense","addExpense",expenseData(3,false),409);}
}
