const {test,beforeEach}=require('node:test'),assert=require('node:assert/strict')
const store=new Map();let cloud,definition,handler,requests=[]
global.Behavior=x=>x;global.getApp=()=>({globalData:{}})
global.wx={getStorageSync:k=>store.get(k)||'',setStorageSync:(k,v)=>store.set(k,structuredClone(v)),request:o=>{requests.push(o);handler(o)},showToast(){},pageScrollTo(){},showModal:o=>o.success({confirm:true})}
const fixture=()=>({id:'ct',version:1,role:'editor',payload:{trip:{id:'t',startDate:'2026-10-09',itinerary:[{id:'day1',date:'2026-10-09',activities:[{id:'a1',name:'西湖',time:'09:00'}]}]},expenses:[{id:'e1',tripId:'t',amount:10,description:'午餐',category:'food',date:'2026-10-09',split:{version:1,payerId:'m1',shares:[{memberId:'m1',cents:500},{memberId:'m2',cents:500}]}}]},ledger:{members:[{id:'m1',name:'甲',paidCents:1000,shareCents:500,balanceCents:500},{id:'m2',name:'乙',paidCents:0,shareCents:500,balanceCents:-500}],suggestions:[{fromId:'m2',toId:'m1',fromName:'乙',toName:'甲',cents:500}],settlements:[],totalCents:1000,sharedCents:1000}})
beforeEach(async()=>{store.clear();requests=[];handler=o=>o.success({statusCode:200,data:{token:'test-token',userId:'u'}});delete require.cache[require.resolve('../services/cloud-service')];cloud=require('../services/cloud-service');await cloud.login('student-a');global.Page=d=>definition=d;delete require.cache[require.resolve('../pages/cloud-editor/cloud-editor')];require('../pages/cloud-editor/cloud-editor');handler=o=>o.success({statusCode:200,data:fixture()});requests=[]})
function page(){return {...definition,data:structuredClone(definition.data),setData(v){Object.assign(this.data,structuredClone(v))}}}
test('view and preview keep integer cents and label ordinary expenses',()=>{const model=require('../services/cloud-editor-model'),view=model.view(fixture(),['m1']);assert.equal(view.total,'10.00');assert.equal(view.aaMembers[0].balance,'应收 ¥5.00');assert.equal(view.aaMembers[0].selected,true);assert.deepEqual(model.preview(view.aaMembers,'0.01',['m2','m1']).map(p=>p.amount),['0.01','0.00']);assert.deepEqual(model.preview(view.aaMembers,'10',['foreign']),[])})
test('page AA edit sends stable payer and participants once and retains expense ID',async()=>{const p=page();await p.onLoad({tripId:'ct'});p.onEditExpense({currentTarget:{dataset:{id:'e1'}}});assert.equal(p.data.payerId,'m1');p.onInput({currentTarget:{dataset:{field:'amount'}},detail:{value:'20'}});await Promise.all([p.onSaveExpense(),p.onSaveExpense()]);const actions=requests.filter(r=>r.url.endsWith('/actions'));assert.equal(actions.length,1);assert.equal(actions[0].data.action,'updateExpense');assert.equal(actions[0].data.data.id,'e1');assert.equal(actions[0].data.data.payerId,'m1');assert.deepEqual(actions[0].data.data.participantIds,['m1','m2']);assert.equal(p.data.expenseId,'')})
test('ambiguous network failure retries same operation and original version after refresh',async()=>{const p=page();await p.onLoad({tripId:'ct'});const data={name:'丙'};let fail=true;handler=o=>{if(o.method==='POST'&&fail)o.fail({});else o.success({statusCode:200,data:{...fixture(),version:2}})};await p.run(()=>p.command('addMember',data));const first=requests.find(r=>r.url.endsWith('/actions')).data;assert.match(p.data.error,/无法连接/);await p.onRefresh();fail=false;await p.run(()=>p.command('addMember',data));const actions=requests.filter(r=>r.url.endsWith('/actions'));assert.deepEqual(actions[1].data,first);assert.equal(p.data.current.version,2)})
test('409 refresh preserves form and next deliberate save uses refreshed version',async()=>{const p=page();await p.onLoad({tripId:'ct'});p.onEditExpense({currentTarget:{dataset:{id:'e1'}}});p.data.amount='20';let conflict=true;handler=o=>o.method==='POST'&&conflict?o.success({statusCode:409,data:{message:'版本已变化'}}):o.success({statusCode:200,data:{...fixture(),version:2}});await p.onSaveExpense();assert.equal(p.data.amount,'20');assert.equal(p.data.expenseId,'e1');assert.match(p.data.error,/已刷新/);conflict=false;await p.onSaveExpense();const actions=requests.filter(r=>r.url.endsWith('/actions'));assert.equal(actions[1].data.version,2);assert.notEqual(actions[0].data.operationId,actions[1].data.operationId)})
test('viewer refuses all command writes locally',async()=>{const p=page();await p.onLoad({tripId:'ct'});p.data.current.role='viewer';await p.run(()=>p.command('deleteExpense',{id:'e1'}));assert.match(p.data.error,/只读/);assert.equal(requests.filter(r=>r.method==='POST').length,0)})
test('activity form retains stable day ID across a day reorder',async()=>{const p=page();await p.onLoad({tripId:'ct'});p.onActivityEdit({currentTarget:{dataset:{day:0,id:'a1'}}});const refreshed=fixture();refreshed.payload.trip.itinerary.unshift({id:'day0',date:'2026-10-08',activities:[]});p.applySnapshot(refreshed);assert.equal(p.data.dayIndex,1);p.data.activityName='断桥';await p.onSaveActivity();const action=requests.find(r=>r.url.endsWith('/actions')).data;assert.equal(action.data.dayId,'day1');assert.equal(action.data.id,'a1');assert.equal(action.data.name,'断桥')})
test('payer identity survives member order changes, missing payer requires selection',async()=>{const p=page();await p.onLoad({tripId:'ct'});p.onEditExpense({currentTarget:{dataset:{id:'e1'}}});const refreshed=fixture();refreshed.ledger.members.reverse();p.applySnapshot(refreshed);assert.equal(p.data.payerId,'m1');assert.equal(p.data.payerIndex,1);refreshed.ledger.members=refreshed.ledger.members.filter(m=>m.id!=='m1');p.applySnapshot(refreshed);assert.equal(p.data.payerId,'')})
