const {test,beforeEach}=require('node:test'),assert=require('node:assert/strict')
const storage=new Map();let cloud,handler,called=[]
global.wx={getStorageSync:k=>storage.has(k)?structuredClone(storage.get(k)):'',setStorageSync:(k,v)=>storage.set(k,structuredClone(v)),request:o=>{called.push(o);handler(o)},login:o=>o.success({code:'wx-code'}),showToast(){},pageScrollTo(){}}
beforeEach(()=>{storage.clear();called=[];handler=o=>o.success({statusCode:200,data:{token:'secret-test-token',userId:'u1',expiresAt:123}});delete require.cache[require.resolve('../services/cloud-service')];cloud=require('../services/cloud-service')})
test('URL changes clear scoped credentials and reject nonlocal HTTP',async()=>{await cloud.login('student-a');assert.equal(cloud.load().userId,'u1');assert.throws(()=>cloud.configure('http://192.168.1.2:8087'),/HTTPS/);cloud.configure('https://travel.example.com');assert.equal(cloud.load().token,'');await assert.rejects(cloud.request('/trips'),/先登录/);assert.equal(called.length,1)})
test('real login uses wx code and no credential header',async()=>{await cloud.login();assert.equal(called[0].data.code,'wx-code');assert.equal(called[0].url,'http://127.0.0.1:8087/api/auth/wechat');assert.equal(called[0].header.Authorization,undefined);await cloud.request('/trips');assert.equal(called[1].header.Authorization,'Bearer secret-test-token')})
test('401 clears session and 409 preserves error instead of mock success',async()=>{await cloud.login('student-a');handler=o=>o.success({statusCode:409,data:{message:'旅行已变化'}});await assert.rejects(cloud.request('/trips/t','PUT',{}),e=>e.status===409&&e.message==='旅行已变化');assert.equal(cloud.load().userId,'u1');handler=o=>o.success({statusCode:401,data:{message:'登录已过期'}});await assert.rejects(cloud.request('/trips'),/过期/);assert.equal(cloud.load().token,'')})
test('transport failure stays visible and logout clears local token even when offline',async()=>{await cloud.login('student-a');handler=o=>o.fail({errMsg:'offline'});await assert.rejects(cloud.request('/trips'),/无法连接/);await assert.rejects(cloud.logout(),/无法连接/);assert.equal(cloud.load().token,'')})
test('upload snapshot filters other trips and preserves real AA payload',async()=>{const trips=require('../services/trip-service'),aa=require('../services/aa-service'),budget=require('../services/budget-service');trips.createTrip({id:'t',destination:'杭州',startDate:'2026-10-09',endDate:'2026-10-09',totalBudget:600});const a=aa.addMember('t','甲'),b=aa.addMember('t','乙');await budget.addExpense({tripId:'t',amount:0.01,description:'午餐',category:'food',date:'2026-10-09',split:aa.makeSplit('t',0.01,a.id,[a.id,b.id])});storage.set('diaries',[{id:'d',tripId:'other',content:'私密'},{id:'d2',tripId:'t',content:'西湖'}]);const payload=cloud.snapshot('t');assert.equal(payload.trip.itinerary[0].date,'2026-10-09');assert.deepEqual(payload.expenses[0].split.shares.map(s=>s.cents),[1,0]);assert.equal(payload.diaries.length,1);assert.equal(payload.diaries[0].content,'西湖');assert.throws(()=>cloud.snapshot('missing'),/不存在/)})
test('page edits cloud snapshot with version and viewer has no write path',async()=>{global.Behavior=x=>x;global.getApp=()=>({globalData:{}});let def;global.Page=x=>def=x;delete require.cache[require.resolve('../pages/cloud/cloud')];require('../pages/cloud/cloud');const current={id:'cloud-t',role:'editor',version:3,payload:{trip:{id:'t',itinerary:[{date:'2026-10-09',activities:[{name:'西湖',time:'09:00'}]}]},expenses:[]}};const page={...def,data:{...structuredClone(def.data),current:structuredClone(current),activities:[{name:'西湖',dayIndex:0,index:0}]},setData(v){Object.assign(this.data,structuredClone(v))}};await cloud.login('student-a');let update;handler=o=>{if(o.method==='PUT'){update=o.data;o.success({statusCode:200,data:current})}else if(o.url.endsWith('/members'))o.success({statusCode:200,data:[]});else o.success({statusCode:200,data:current})};wx.showModal=o=>o.success({confirm:true,content:'断桥'});const run=page.run;page.run=function(fn){this.pending=run.call(this,fn);return this.pending};page.onEditActivity({currentTarget:{dataset:{index:0}}});await page.pending;assert.equal(update.version,3);assert.equal(update.payload.trip.itinerary[0].activities[0].name,'断桥');assert.equal(current.payload.trip.itinerary[0].activities[0].name,'西湖');page.data.current.role='viewer';update=null;page.onEditActivity({currentTarget:{dataset:{index:0}}});assert.equal(update,null)})
