const {test,beforeEach}=require('node:test'),assert=require('node:assert/strict')
const data=new Map();let fail=false
global.wx={getStorageSync:k=>data.has(k)?structuredClone(data.get(k)):'',setStorageSync:(k,v)=>{if(fail)throw Error('full');data.set(k,structuredClone(v))},showToast(){},showModal(){}}
const trips=require('../services/trip-service'),aa=require('../services/aa-service'),budget=require('../services/budget-service')
let a,b
beforeEach(()=>{data.clear();fail=false;trips.createTrip({id:'t',destination:'杭州',totalBudget:100});a=aa.addMember('t','甲');b=aa.addMember('t','乙')})
async function expense(){return budget.addExpense({tripId:'t',amount:10,description:'午餐',category:'food',date:'2026-10-09',split:aa.makeSplit('t',10,a.id,[a.id,b.id])})}
test('rename preserves identity, old shares and settlements, rejects duplicates',async()=>{const e=await expense();aa.recordSettlement('t',aa.getLedger('t').suggestions[0],'s');aa.renameMember('t',a.id,'小甲');assert.equal(aa.getLedger('t').members[0].id,a.id);assert.equal(aa.getLedger('t').members[0].name,'小甲');assert.ok(aa.getLedger('t').members.every(m=>m.balanceCents===0));assert.deepEqual((await budget.getExpenses('t'))[0],e);assert.throws(()=>aa.renameMember('t',a.id,'乙'),/重复/);assert.throws(()=>aa.renameMember('t',a.id,' '),/名字/);assert.throws(()=>aa.renameMember('t','foreign','丙'),/不存在/)})
test('editing paid AA expense updates budget and debts without erasing transfer',async()=>{const e=await expense();aa.recordSettlement('t',aa.getLedger('t').suggestions[0],'s');await budget.updateExpense(e.id,'t',{amount:20,split:aa.makeSplit('t',20,a.id,[a.id,b.id])},e);const ledger=aa.getLedger('t');assert.equal(ledger.sharedCents,2000);assert.deepEqual(ledger.members.map(m=>m.balanceCents),[500,-500]);assert.equal(ledger.settlements.length,1);assert.equal((await budget.getBudgetOverview('t')).totalSpent,20);assert.equal((await budget.getExpenses('t')).length,1)})
test('edit payer and participants keeps exact cents and original ID',async()=>{const e=await expense();const next=await budget.updateExpense(e.id,'t',{amount:0.01,split:aa.makeSplit('t',0.01,b.id,[a.id]),description:'车费',category:'transport'},e);assert.equal(next.id,e.id);assert.deepEqual(aa.getLedger('t').members.map(m=>m.balanceCents),[-1,1])})
test('stale, missing, invalid edits and type conversions do not mutate',async()=>{const e=await expense();for(const updates of [{amount:11},{split:undefined},{date:'2026-02-30'},{amount:0},{category:'fake'},{description:' '}])await assert.rejects(budget.updateExpense(e.id,'t',updates,e));assert.deepEqual((await budget.getExpenses('t'))[0],e);await assert.rejects(budget.updateExpense(e.id,'other',{},e),/不存在/);await budget.updateExpense(e.id,'t',{description:'新说明'},e);await assert.rejects(budget.updateExpense(e.id,'t',{description:'旧页面'},e),/已变化/)})
test('ordinary edit never converts to AA and ignores identity updates',async()=>{const e=await budget.addExpense({tripId:'t',amount:2,description:'饮料',category:'food',date:'2026-10-09'});const next=await budget.updateExpense(e.id,'t',{amount:3,id:'changed',tripId:'changed'},e);assert.equal(next.id,e.id);assert.equal(next.tripId,'t');assert.equal((await budget.getBudgetOverview('t')).totalSpent,3);await assert.rejects(budget.updateExpense(e.id,'t',{split:aa.makeSplit('t',3,a.id,[a.id])},next),/类型/)})
test('write failure preserves expense and member name',async()=>{const e=await expense();fail=true;await assert.rejects(budget.updateExpense(e.id,'t',{description:'修改'},e));assert.throws(()=>aa.renameMember('t',a.id,'修改'));fail=false;assert.deepEqual((await budget.getExpenses('t'))[0],e);assert.equal(aa.getLedger('t').members[0].name,'甲')})
test('AA page opens original expense, saves once, and cancel leaves record intact',async()=>{const e=await expense();global.Behavior=x=>x;global.getApp=()=>({globalData:{}});wx.pageScrollTo=()=>{};let def;global.Page=x=>def=x;require('../pages/aa/aa');const page={...def,data:structuredClone(def.data),setData(v){Object.assign(this.data,structuredClone(v))}};page.onLoad({tripId:'t'});await page.refresh();page.onEdit({currentTarget:{dataset:{id:e.id}}});assert.equal(page.data.editingId,e.id);assert.deepEqual(page.data.selectedIds,[a.id,b.id]);page.onInput({currentTarget:{dataset:{field:'amount'}},detail:{value:'20'}});await Promise.all([page.onSave(),page.onSave()]);assert.equal(page.data.editingId,'');assert.equal((await budget.getExpenses('t')).length,1);assert.equal((await budget.getBudgetOverview('t')).totalSpent,20);page.onEdit({currentTarget:{dataset:{id:e.id}}});page.onCancelEdit();assert.equal((await budget.getBudgetOverview('t')).totalSpent,20)})
test('budget page reuses ordinary form and directs AA edits to ledger',async()=>{const e=await budget.addExpense({tripId:'t',amount:2,description:'饮料',category:'food',date:'2026-10-09'});global.Behavior=x=>x;let def;global.Page=x=>def=x;require('../pages/budget/budget');const page={...def,data:structuredClone(def.data),setData(v){Object.assign(this.data,structuredClone(v))}};page.data.tripId='t';await page.loadData();page.onEditExpense(e.id);page.data.newExpense.amount='3';await page.onSaveExpense();assert.equal((await budget.getBudgetOverview('t')).totalSpent,3);const shared=await expense();await page.loadData();let url;wx.navigateTo=o=>url=o.url;page.onEditExpense(shared.id);assert.match(url,/pages\/aa\/aa/);assert.equal((await budget.getExpenses('t')).length,2)})
