const cloud=require('../../services/cloud-service')
const tripService=require('../../services/trip-service')
const themeBehavior=require('../../utils/theme-behavior')
Page({
 behaviors:[themeBehavior],
 data:{baseUrl:'',userId:'',busy:false,error:'',localTrips:[],localIndex:0,trips:[],current:null,activities:[],expenses:[],members:[],inviteToken:'',inviteRoleIndex:0,inviteRoles:['只读成员','可编辑成员'],canShare:false,devEnabled:false},
 onLoad(options){const session=cloud.load();this.setData({baseUrl:session.baseUrl,userId:session.userId,inviteToken:options.invite||''});this.initialize()},
 onShow(){if(this._openedEditor){this._openedEditor=false;return this.onRefresh()}},
 async initialize(){try{this.setData({localTrips:tripService.getAllTrips()});const health=await cloud.request('/health','GET',undefined,false);this.setData({devEnabled:health.devLogin===true});if(this.data.userId)await this.list()}catch(e){this.setData({error:e.message})}},
 onInput(e){const field=e.currentTarget.dataset.field;if(['baseUrl','inviteToken'].includes(field))this.setData({[field]:e.detail.value})},
 onLocal(e){this.setData({localIndex:Number(e.detail.value)})},
 onRole(e){this.setData({inviteRoleIndex:Number(e.detail.value)})},
 async run(action){if(this.data.busy)return;this.setData({busy:true,error:''});try{await action()}catch(e){this.setData({error:e.message});if(e.status===401)this.setData({userId:'',current:null,activities:[],expenses:[],members:[]})}finally{this.setData({busy:false})}},
 onConnect(){return this.run(async()=>{this._issuedInvite=null;this.setData({canShare:false});const session=cloud.configure(this.data.baseUrl);this.setData({userId:session.userId,current:null,trips:[],devEnabled:false,activities:[],expenses:[],members:[]});const health=await cloud.request('/health','GET',undefined,false);this.setData({devEnabled:health.devLogin===true});if(session.userId)await this.list()})},
 onLogin(){return this.run(async()=>{this._issuedInvite=null;this.setData({canShare:false});cloud.configure(this.data.baseUrl);const session=await cloud.login();this.setData({userId:session.userId,current:null});await this.list()})},
 onDevLogin(e){return this.run(async()=>{this._issuedInvite=null;this.setData({canShare:false});cloud.configure(this.data.baseUrl);const session=await cloud.login(e.currentTarget.dataset.account);this.setData({userId:session.userId,current:null,activities:[],expenses:[],members:[]});await this.list()})},
 onLogout(){return this.run(async()=>{this._issuedInvite=null;this.setData({canShare:false});try{await cloud.logout()}finally{this.setData({userId:'',trips:[],current:null,activities:[],expenses:[],members:[]})}})},
 async list(){this.setData({trips:await cloud.request('/trips')})},
 onRefresh(){return this.run(async()=>{await this.list();if(this.data.current)await this.open(this.data.current.id)})},
 async open(id){if(this._issuedInvite&&this._issuedInvite.tripId!==id){this._issuedInvite=null;this.setData({canShare:false})}const current=await cloud.request('/trips/'+encodeURIComponent(id));const members=await cloud.request('/trips/'+encodeURIComponent(id)+'/members');const activities=[];current.payload.trip.itinerary.forEach((day,dayIndex)=>day.activities.forEach((a,index)=>activities.push({...a,date:day.date,dayIndex,index})));this.setData({current,activities,members:members.map(m=>({...m,label:m.userId===this.data.userId?'我':m.userId.slice(0,8)})),expenses:current.payload.expenses})},
 onOpen(e){return this.run(()=>this.open(e.currentTarget.dataset.id))},
 onUpload(){return this.run(async()=>{const trip=this.data.localTrips[this.data.localIndex];if(!trip)throw Error('请先在本机创建旅行');const payload=cloud.snapshot(trip.id);const raw=JSON.stringify(payload);if(!this._pendingUpload||this._pendingUpload.raw!==raw)this._pendingUpload={raw,operationId:'upload-'+Date.now()+'-'+Math.random().toString(36).slice(2)};const result=await cloud.request('/trips','POST',{payload,operationId:this._pendingUpload.operationId});await this.list();await this.open(result.id)})},
 onInvite(){return this.run(async()=>{const current=this.data.current;const invitation=await cloud.request('/trips/'+current.id+'/invites','POST',{role:this.data.inviteRoleIndex===0?'viewer':'editor'});this._issuedInvite={...invitation,tripId:current.id};this.setData({inviteToken:invitation.token,canShare:true});wx.showToast({title:'邀请有效期 24 小时',icon:'none'})})},
 onCopyInvite(){if(this.data.inviteToken)wx.setClipboardData({data:this.data.inviteToken})},
 onJoin(){return this.run(async()=>{const result=await cloud.request('/invites/join','POST',{token:this.data.inviteToken.trim()});await this.list();await this.open(result.id)})},
 onRevoke(){return this.run(async()=>{if(!this._issuedInvite)throw Error('请先生成邀请');await cloud.request('/trips/'+this._issuedInvite.tripId+'/invites/revoke','POST',{token:this._issuedInvite.token});this._issuedInvite=null;this.setData({inviteToken:'',canShare:false});wx.showToast({title:'邀请已撤销',icon:'success'})})},
 onMemberRole(e){if(this.data.busy)return;const current=this.data.current,userId=e.currentTarget.dataset.id;wx.showActionSheet({itemList:['设为只读','设为可编辑'],success:res=>this.run(async()=>{await cloud.request('/trips/'+current.id+'/members/'+encodeURIComponent(userId),'PUT',{role:res.tapIndex===0?'viewer':'editor'});await this.open(current.id)})})},
 onEditActivity(e){if(this.data.busy||!this.data.current||this.data.current.role==='viewer')return;const item=this.data.activities[e.currentTarget.dataset.index],original=JSON.parse(JSON.stringify(this.data.current));if(!item)return;wx.showModal({title:'修改活动名称',editable:true,placeholderText:item.name,success:res=>{if(!res.confirm)return;this.run(async()=>{const name=String(res.content||'').trim();if(!name)throw Error('请填写活动名称');original.payload.trip.itinerary[item.dayIndex].activities[item.index].name=name;const result=await cloud.request('/trips/'+original.id,'PUT',{version:original.version,payload:original.payload});await this.open(result.id)})}})},
 onManage(){if(this.data.current){this._openedEditor=true;wx.navigateTo({url:'/pages/cloud-editor/cloud-editor?tripId='+encodeURIComponent(this.data.current.id),fail:()=>{this._openedEditor=false}})}},
 onShareAppMessage(){return {title:'一起规划大学生旅行',path:'/pages/cloud/cloud'+(this._issuedInvite&&this.data.current&&this._issuedInvite.tripId===this.data.current.id?'?invite='+encodeURIComponent(this._issuedInvite.token):'')}}
})
