CREATE TABLE IF NOT EXISTS app_users (id VARCHAR(64) PRIMARY KEY, openid VARCHAR(128) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,expires_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS trips (id VARCHAR(64) PRIMARY KEY,owner_id VARCHAR(64) NOT NULL,payload CLOB NOT NULL,version BIGINT NOT NULL,operation_id VARCHAR(100) NOT NULL,request_hash VARCHAR(64) NOT NULL, UNIQUE(owner_id,operation_id));
CREATE TABLE IF NOT EXISTS members (trip_id VARCHAR(64) NOT NULL,user_id VARCHAR(64) NOT NULL,role VARCHAR(10) NOT NULL, PRIMARY KEY(trip_id,user_id));
CREATE TABLE IF NOT EXISTS invites (token_hash VARCHAR(64) PRIMARY KEY,trip_id VARCHAR(64) NOT NULL,role VARCHAR(10) NOT NULL,expires_at BIGINT NOT NULL,revoked BOOLEAN NOT NULL DEFAULT FALSE);

CREATE TABLE IF NOT EXISTS operations (trip_id VARCHAR(64) NOT NULL,user_id VARCHAR(64) NOT NULL,operation_id VARCHAR(100) NOT NULL,request_hash VARCHAR(64) NOT NULL,PRIMARY KEY(trip_id,user_id,operation_id));
